Algoritmo "testeSaida"
//  
//  

Var

idade : inteiro
preco1, preco2 : real
produto1, produto2, genero : caractere
codigo : inteiro





Inicio

produto1 <- "computador"
produto2 <- "TV"
genero <- "F"
preco1 <- 2100.50
preco2 <- 1830.0

escreval("Produtos: ")

escreval("O produto ", produto1, " custa R$", preco1)
escreval("")
escreval("O produto ", produto2, " custa R$", preco2)
escreval("")
escreval("Codigo" , codigo)
escreval("Dados da pessoa: ", genero, " e idade ", idade)



Fimalgoritmo